openapi: 3.0.1
info:
  title: data adapter for recipes SDE
  version: "1.0.0"
  description: |-
    data adapter for recipes API for SDE project

servers:
  - url: http://127.0.0.1:3002
    description: local server

paths:
  /recipes/random:
    get:
      summary: get random recipes
      tags:
        - Recipes
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Recipes"
          description: successful operation

components:
  schemas:
    Recipes:
      type: object
      properties:
        title:
          type: string
          format: string
        image:
          type: string
          format: string
        instructions:
          type: string
          format: string
        ingredients:
          type: array
          items:
            $ref: "#/components/schemas/Ingredients"
    Ingredients:
      type: object
      properties:
        name:
          type: string
          format: string
        quantity:
          type: number
          format: number
        unit:
          type: string
          format: string
        id:
          type: number
          format: number
